### ISSUE TITLE
All-End Config Option 

### ISSUE THREAD

**Issue by DeathShadez** [PolyhedralDev/BetterEnd-Public#59]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I love the Aether and everything it beholds, but I'm asking for those who don't prefer it in particular. I'm asking for a config option that is basically the opposite of the **all-aether** and would be the **all-end** for those who don't seem to like the idea of the Aether in the End, but may perhaps prefer for it to be in it's own dimension. They will just have to re-enable end cities to fit for their case of elytras since Gold Dungeons no longer generate. Biomes like the Shattered forest and Shattered End will still generate. I don't know how the void / starfield biome would come into play. Maybe void zones like regular void biomes. The main island also continues to be kept.

**Describe alternatives you've considered**
Adapt or change to how you seek fit.

**Comment by dfsek** [comment]
I'm assuming this would keep the main End island? (the all-aether option does away with the main End island)

**Comment by DeathShadez** [comment]
Yea. This would keep the main island. Forgot to mention that.

**Comment by dfsek** [comment]
Alright, will probably be called aether.disable-aether instead, but should be rather simple to implement.
