### ISSUE TITLE
API for Gold Dungeon Boss fight

### ISSUE THREAD

**Issue by l3st4tPlugins** [PolyhedralDev/BetterEnd-Public#62]
**Is your feature request related to a problem? Please describe.**
No. I just want an easy way to spawn a custom mob when the Gold Dungeon chest is opened, as I don't use MythicMobs, I use my own custom mobs.

**Describe the solution you'd like**
An event that plugins can listen to, for example, EndBossSpawnEvent, with a few methods such as #getSpawnLocation, #getPlayer.

**Describe alternatives you've considered**
Making a fake MythicMobs plugin that just calls my plugin's methods, but that's just not easy to maintain. What if MythicMobs changes its methods?

**Additional context**
None.

**Comment by dfsek** [comment]
This will most likely be implemented, though under the name BossChestOpenEvent.

Will probably have these methods:
#getSpawnLocation - the location at which the boss will spawn. 
#getChestLocation - the location of the chest triggering the spawn.
#getName - the name of the boss set in config.yml.
#getPlayer - the player opening the chest.
#isTimeoutExceeded - whether or not the timeout for respawning has been exceeded (for premium only, free version would always return true)
#getLastOpenTime - returns the timestamp of the last opening of the chest (for premium only, free version would throw some exception)
#getTimeout - returns the timeout ser in config.yml (for premium only, free version would throw some exception)

Thoughts/suggestions?

**Comment by l3st4tPlugins** [comment]
Yes, that's exactly what I need.
