### ISSUE TITLE
More randomization and variation in floating island shapes

### ISSUE THREAD

**Issue by Fr0sto** [PolyhedralDev/BetterEnd-Public#71]
**Is your feature request related to a problem? Please describe.**
As I explore the end dimension, the geometric perfection and uniformity of the undersides of the custom floating islands sticks out like a sore thumb to me.

**Describe the solution you'd like**
Different shaped islands, jagged edges, rough sides... anything. Unless this look was intentional on your part, and is supposed to be part of the aesthetic.

**Additional context**
Just an example of what I mean- a screenshot of a totally random location that is representative of the "problem" I have described: ![2020-08-14_20 28 25](https://user-images.githubusercontent.com/15222806/90301341-45ad2c80-de6d-11ea-8c61-b56dd1d854f3.png)

**Comment by dfsek** [comment]
This is a product of the rather ancient terrain gen algorithm that is in the process of being completely redone (for 4.0.0).

**Comment by dfsek** [comment]
The End most likely won't be changed too much, but I may make some changes to how the Aether generates.

**Comment by dfsek** [comment]
![2020-08-31_15 17 02](https://user-images.githubusercontent.com/39248502/91774180-14d33400-eb9d-11ea-9c80-351e7a659a48.png)

4.0.0's new terrain generation. There will be a lot more ways to customize it than in previous versions. Is this what you had in mind? (You can join the Discord to see more images of the new terrain gen)
