### ISSUE TITLE
Hard Crash while Exploring Pregenerated Chunks

### ISSUE THREAD

**Issue by EuanM199** [PolyhedralDev/BetterEnd-Public#74]
**Describe the bug**
The Betterend plugin Hard Crashed the Server

**To Reproduce**
1. Go to 'End'
2. Explore, sorry dont have much other than that

**Versions**
Git Paper Version 145 1.16.2
Betterend V3.7.0

Here is the MC Server Crash Report
https://pastebin.com/WjumuaGc
and the last part of  Console 
https://mcpaste.io/6cefa74a89c6b175

**Comment by dfsek** [comment]
Can you give me your world seed, and the coordinates at which the crash occurred?

**Comment by EuanM199** [comment]
World seed 4874058614073277837

Location in the end was x=-2989.50, y=67.00, z=-2470.50, cx=-187, cz=-155, tl=27831
