### ISSUE TITLE
Generation Issues

### ISSUE THREAD

**Issue by Rhbarber** [PolyhedralDev/BetterEnd-Public#76]
**Describe the bug**
Issue with End world/dimension generation.

**To Reproduce**
1. Create a new End
2. Use a pregenerator like ChunkMaster
3. Crash.

**Expected behavior**
Behave as normal, no issue.

**Screenshots**
https://pastebin.com/nUTghidE

**Versions**
Please submit the output of the following commands:

`>....=>.... [20:30:26 INFO]: This server is running Paper version git-Paper-185 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
>.... [20:30:26 INFO]: Checking version, please wait...
>.... [20:30:27 INFO]: Previous version: git-Paper-182 (MC: 1.16.2)
>.... [20:30:27 INFO]: You are 1 version(s) behind

`[BetterEnd] Este servidor está usando la versión v4.0.0 de BetterEnd`

**Do not submit just the version number, submit the entire command output!**

**Additional context**

**Comment by dfsek** [comment]
Could you enable debug mode and attempt to reproduce, then pastebin your entire console?

**Comment by Rhbarber** [comment]
[crash-2020-09-07_21.19.40-server.txt](https://github.com/PolyhedralDev/BetterEnd-Public/files/5186027/crash-2020-09-07_21.19.40-server.txt)

https://pastebin.com/Uy9KQ99B

**Comment by dfsek** [comment]
Fixed in 4.0.1
